exports.statusCodes = {
  success: 200,
  created: 201,
  noContent: 204,
  notModified: 304,
  badRequest: 400,
  unAuthorized: 401,
  forbidden: 403,
  notFound: 404,
  conflict: 409,
  serverError: 500,
  user: 'USER',
  active: 'ACTIVE',
  suspended: 'SUSPENDED',
  pending: 'PENDING',
  inactive: 'INACTIVE',
  admin: 'ADMIN',
  invalid: 'INVALID',
  expired: 'EXPIRED',
  delete: 'DELETE',
  failed: 'FAILED',
  cancelled: 'CANCELLED',
  successful: 'SUCCESSFUL',
  postponed: 'POSTPONED',
  inprogress: 'IN PROGRESS',
  finished: 'FINISHED',
  deleted: 'DELETED',
  completed: 'COMPLETED',
};
